// Flat config — extends the config generated by @nuxt/eslint (after `nuxt prepare`).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // We render Markdown that is sanitised with DOMPurify before binding.
    'vue/no-v-html': 'off',
    // Pages and app.vue are single-word by Nuxt convention.
    'vue/multi-word-component-names': 'off',
  },
})
